# Generated by Django 4.2.23 on 2025-09-24 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSettings',
            fields=[
                ('job_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('queue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('function_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('repeat_interval', models.TextField(blank=True, max_length=4000, null=True)),
                ('max_run_duration', models.DurationField(blank=True, null=True)),
                ('max_run', models.IntegerField(blank=True, null=True)),
                ('max_failure', models.IntegerField(blank=True, null=True)),
                ('retry_delay', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('is_enable', models.BooleanField(default=False)),
                ('auto_drop', models.BooleanField(default=False)),
                ('restart_on_failure', models.BooleanField(default=False)),
                ('restartable', models.BooleanField(default=False)),
                ('run_account', models.CharField(blank=True, max_length=255, null=True)),
                ('run_forever', models.BooleanField(default=False)),
                ('job_operation', models.CharField(blank=True, max_length=255, null=True)),
                ('run_number', models.IntegerField(default=0)),
                ('last_task_done', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, max_length=255, null=True)),
                ('workflow_delay', models.IntegerField(blank=True, default=0, null=True)),
                ('job_type', models.CharField(choices=[('REST_API', 'REST API'), ('EXECUTABLE', 'Executable')], default='EXECUTABLE', max_length=50)),
                ('job_action', models.TextField(blank=True, null=True)),
                ('job_body', models.JSONField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('last_run_date', models.DateTimeField(blank=True, null=True)),
                ('next_run_date', models.DateTimeField(blank=True, null=True)),
                ('ignore_result', models.BooleanField(default=False)),
                ('last_result', models.CharField(choices=[('created', 'Created'), ('succeed', 'Succeed'), ('failed', 'Failed'), ('none', 'None')], default='created', max_length=255)),
                ('workflow_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'celery_job_settings',
            },
        ),
        migrations.CreateModel(
            name='TaskWorkflow',
            fields=[
                ('workflow_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('repeat_interval', models.TextField(max_length=4000)),
                ('timezone', models.CharField(blank=True, max_length=255, null=True)),
                ('queue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('last_run_date', models.DateTimeField(blank=True, null=True)),
                ('next_run_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRunDetail',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('run_forever', models.BooleanField(default=False)),
                ('workflow_id', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('run_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'celery_workflow_run_detail',
            },
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_duration', models.DurationField(blank=True, null=True)),
                ('run_date', models.DateTimeField()),
                ('task_name', models.CharField(max_length=255)),
                ('run_account', models.CharField(blank=True, max_length=255, null=True)),
                ('retry_count', models.IntegerField(blank=True, default=0, null=True)),
                ('run_number', models.IntegerField(default=0)),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('succeed', 'Succeed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('stopped', 'Stopped'), ('skipped', 'Skipped'), ('none', 'None')], default='created', max_length=255)),
                ('already_run', models.BooleanField(default=False)),
                ('soft_delete', models.BooleanField(default=False)),
                ('manually_run', models.BooleanField(default=False)),
                ('previous_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('task_result', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celerytasks.jobsettings')),
            ],
            options={
                'db_table': 'celery_task_detail',
            },
        ),
    ]
