"""empty message

Revision ID: 0414fb07ab16
Revises: 2ce803af2821
Create Date: 2025-09-11 10:01:14.610425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0414fb07ab16'
down_revision = '2ce803af2821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_workflow', sa.Column('last_run_date', sa.BigInteger(), nullable=True))
    op.add_column('scheduler_workflow', sa.Column('next_run_date', sa.BigInteger(), nullable=True))
    op.create_index('idx_last_run_date', 'scheduler_workflow', ['last_run_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_last_run_date', table_name='scheduler_workflow')
    op.drop_column('scheduler_workflow', 'next_run_date')
    op.drop_column('scheduler_workflow', 'last_run_date')
    # ### end Alembic commands ###
