"""empty message

Revision ID: 1310f247f3b5
Revises: 903045204cb8
Create Date: 2025-07-18 09:22:12.401057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '1310f247f3b5'
down_revision = '903045204cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("CREATE EXTENSION IF NOT EXISTS pg_trgm;"))
    op.drop_index(op.f('idx_log_group_id'), table_name='scheduler_job_run_logs')
    op.create_index('idx_celery_task_name', 'scheduler_job_run_logs', ['celery_task_name'], unique=False)
    op.create_index('idx_job_name_gin', 'scheduler_job_run_logs', ['job_name'], unique=False, postgresql_using='gin', postgresql_ops={'job_name': 'gin_trgm_ops'})
    op.create_index('idx_operation_gin', 'scheduler_job_run_logs', ['operation'], unique=False, postgresql_using='gin', postgresql_ops={'operation': 'gin_trgm_ops'})
    op.create_index('idx_req_start_date', 'scheduler_job_run_logs', ['req_start_date'], unique=False)
    op.create_index('idx_status_gin', 'scheduler_job_run_logs', ['status'], unique=False, postgresql_using='gin', postgresql_ops={'status': 'gin_trgm_ops'})
    op.create_index('idx_job_comments_gin', 'scheduler_jobs', ['job_comments'], unique=False, postgresql_using='gin', postgresql_ops={'job_comments': 'gin_trgm_ops'})
    op.create_index('idx_repeat_interval_gin', 'scheduler_jobs', ['repeat_interval'], unique=False, postgresql_using='gin', postgresql_ops={'repeat_interval': 'gin_trgm_ops'})
    op.create_index('idx_email_addr', 'scheduler_users', ['email_addr'], unique=False)
    op.create_index('idx_user_name', 'scheduler_users', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_name', table_name='scheduler_users')
    op.drop_index('idx_email_addr', table_name='scheduler_users')
    op.drop_index('idx_repeat_interval_gin', table_name='scheduler_jobs', postgresql_using='gin', postgresql_ops={'repeat_interval': 'gin_trgm_ops'})
    op.drop_index('idx_job_comments_gin', table_name='scheduler_jobs', postgresql_using='gin', postgresql_ops={'job_comments': 'gin_trgm_ops'})
    op.drop_index('idx_status_gin', table_name='scheduler_job_run_logs', postgresql_using='gin', postgresql_ops={'status': 'gin_trgm_ops'})
    op.drop_index('idx_req_start_date', table_name='scheduler_job_run_logs')
    op.drop_index('idx_operation_gin', table_name='scheduler_job_run_logs', postgresql_using='gin', postgresql_ops={'operation': 'gin_trgm_ops'})
    op.drop_index('idx_job_name_gin', table_name='scheduler_job_run_logs', postgresql_using='gin', postgresql_ops={'job_name': 'gin_trgm_ops'})
    op.drop_index('idx_celery_task_name', table_name='scheduler_job_run_logs')
    op.create_index(op.f('idx_log_group_id'), 'scheduler_job_run_logs', ['group_id'], unique=False)
    # ### end Alembic commands ###
