"""empty message

Revision ID: 2ce803af2821
Revises: ee2c9930628c
Create Date: 2025-08-29 19:49:29.463729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce803af2821'
down_revision = 'ee2c9930628c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_workflow_run_id', 'scheduler_job_run_logs', ['workflow_run_id'], unique=False)
    op.drop_constraint(op.f('scheduler_job_run_logs_workflow_run_id_fkey'), 'scheduler_job_run_logs', type_='foreignkey')
    op.create_foreign_key(None, 'scheduler_job_run_logs', 'scheduler_workflow_run', ['workflow_run_id'], ['workflow_run_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduler_job_run_logs', type_='foreignkey')
    op.create_foreign_key(op.f('scheduler_job_run_logs_workflow_run_id_fkey'), 'scheduler_job_run_logs', 'scheduler_workflow_run', ['workflow_run_id'], ['workflow_run_id'])
    op.drop_index('idx_workflow_run_id', table_name='scheduler_job_run_logs')
    # ### end Alembic commands ###
