"""empty message

Revision ID: 903045204cb8
Revises: b679165744f2
Create Date: 2025-07-15 11:33:48.085457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903045204cb8'
down_revision = 'b679165744f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_group_job_system_id', 'scheduler_job_run_logs', ['group_id', 'job_id', 'system_id'], unique=False)
    op.create_index('idx_log_group_id', 'scheduler_job_run_logs', ['group_id'], unique=False)
    op.create_index('idx_status', 'scheduler_job_run_logs', ['status'], unique=False)
    op.create_index('idx_group_id_is_enabled_system_id_job_id', 'scheduler_jobs', ['group_id', 'is_enabled', 'system_id', 'job_id'], unique=False)
    op.create_index('idx_last_start_date', 'scheduler_jobs', ['last_start_date'], unique=False)
    op.create_foreign_key(None, 'scheduler_jobs', 'scheduler_workflow_priority_group', ['priority_group_id'], ['id'])
    op.create_index('idx_user_id', 'scheduler_related_group_user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id', table_name='scheduler_related_group_user')
    op.drop_constraint(None, 'scheduler_jobs', type_='foreignkey')
    op.drop_index('idx_last_start_date', table_name='scheduler_jobs')
    op.drop_index('idx_group_id_is_enabled_system_id_job_id', table_name='scheduler_jobs')
    op.drop_index('idx_status', table_name='scheduler_job_run_logs')
    op.drop_index('idx_log_group_id', table_name='scheduler_job_run_logs')
    op.drop_index('idx_group_job_system_id', table_name='scheduler_job_run_logs')
    # ### end Alembic commands ###
