"""empty message

Revision ID: b19f78fa86c0
Revises: 0414fb07ab16
Create Date: 2025-09-16 18:59:23.087825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19f78fa86c0'
down_revision = '0414fb07ab16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_actual_start_date', 'scheduler_job_run_logs', ['actual_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_actual_start_date', table_name='scheduler_job_run_logs')
    # ### end Alembic commands ###
