"""empty message

Revision ID: b679165744f2
Revises: 
Create Date: 2025-01-22 14:09:11.759191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b679165744f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_type', sa.Integer(), nullable=True),
    sa.Column('user_status', sa.Boolean(), nullable=True),
    sa.Column('user_pwd', sa.String(), nullable=True),
    sa.Column('celp_tlno', sa.String(), nullable=True),
    sa.Column('email_addr', sa.String(), nullable=True),
    sa.Column('lgin_fail_ncnt', sa.Integer(), nullable=True),
    sa.Column('last_pwd_chg_date', sa.BigInteger(), nullable=True),
    sa.Column('last_lgin_timr', sa.BigInteger(), nullable=True),
    sa.Column('frst_reg_date', sa.BigInteger(), nullable=True),
    sa.Column('frst_reg_user_id', sa.String(), nullable=True),
    sa.Column('last_reg_user_id', sa.String(), nullable=True),
    sa.Column('last_chg_date', sa.BigInteger(), nullable=True),
    sa.Column('last_activity_time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='user_table_unique')
    )
    op.create_table('scheduler_workflow_priority_group',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('latest_status', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('ignore_result', sa.Boolean(), nullable=True),
    sa.Column('frst_reg_date', sa.BigInteger(), nullable=True),
    sa.Column('frst_reg_user_id', sa.String(), nullable=True),
    sa.Column('last_reg_user_id', sa.String(), nullable=True),
    sa.Column('last_chg_date', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduler_job_groups',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(length=128), nullable=True),
    sa.Column('group_comments', sa.String(length=4000), nullable=True),
    sa.Column('frst_reg_date', sa.BigInteger(), nullable=True),
    sa.Column('frst_reg_user_id', sa.String(), nullable=True),
    sa.Column('last_chg_date', sa.BigInteger(), nullable=True),
    sa.Column('last_reg_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['frst_reg_user_id'], ['scheduler_users.id'], ),
    sa.ForeignKeyConstraint(['last_reg_user_id'], ['scheduler_users.id'], ),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_name', name='group_table_unique')
    )
    op.create_table('scheduler_job_servers',
    sa.Column('system_id', sa.String(), nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=True),
    sa.Column('host_name', sa.String(length=128), nullable=True),
    sa.Column('host_ip_addr', sa.String(length=128), nullable=True),
    sa.Column('secondary_host_ip_addr', sa.String(length=128), nullable=True),
    sa.Column('system_comments', sa.String(length=4000), nullable=True),
    sa.Column('queue_name', sa.String(), nullable=True),
    sa.Column('folder_path', sa.String(), nullable=True),
    sa.Column('secondary_folder_path', sa.String(), nullable=True),
    sa.Column('ssh_user', sa.String(), nullable=True),
    sa.Column('frst_reg_date', sa.BigInteger(), nullable=True),
    sa.Column('frst_reg_user_id', sa.String(), nullable=True),
    sa.Column('last_chg_date', sa.BigInteger(), nullable=True),
    sa.Column('last_reg_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['frst_reg_user_id'], ['scheduler_users.id'], ),
    sa.ForeignKeyConstraint(['last_reg_user_id'], ['scheduler_users.id'], ),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('system_name', name='server_table_unique')
    )
    op.create_table('scheduler_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('job_name', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.BigInteger(), nullable=True),
    sa.Column('end_date', sa.BigInteger(), nullable=True),
    sa.Column('repeat_interval', sa.String(length=4000), nullable=True),
    sa.Column('max_run_duration', sa.Interval(), nullable=True),
    sa.Column('max_run', sa.Integer(), nullable=True),
    sa.Column('max_failure', sa.Integer(), nullable=True),
    sa.Column('retry_delay', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_drop', sa.Boolean(), nullable=True),
    sa.Column('restart_on_failure', sa.Boolean(), nullable=True),
    sa.Column('restartable', sa.Boolean(), nullable=True),
    sa.Column('job_comments', sa.String(length=4000), nullable=True),
    sa.Column('job_type', sa.String(length=16), nullable=True),
    sa.Column('job_action', sa.String(length=4000), nullable=True),
    sa.Column('job_body', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('last_start_date', sa.BigInteger(), nullable=True),
    sa.Column('next_run_date', sa.BigInteger(), nullable=True),
    sa.Column('last_run_duration', sa.Interval(), nullable=True),
    sa.Column('current_state', sa.String(length=20), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('priority_group_id', sa.String(), nullable=True),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('ignore_result', sa.Boolean(), nullable=True),
    sa.Column('frst_reg_date', sa.BigInteger(), nullable=True),
    sa.Column('frst_reg_user_id', sa.String(), nullable=True),
    sa.Column('last_chg_date', sa.BigInteger(), nullable=True),
    sa.Column('last_reg_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['frst_reg_user_id'], ['scheduler_users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['scheduler_job_groups.group_id'], ),
    sa.ForeignKeyConstraint(['last_reg_user_id'], ['scheduler_users.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['scheduler_job_servers.system_id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('job_name', name='job_table_unique')
    )
    op.create_table('scheduler_related_group_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['scheduler_job_groups.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['scheduler_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduler_workflow',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_name', sa.String(), nullable=True),
    sa.Column('latest_status', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('frst_reg_date', sa.BigInteger(), nullable=True),
    sa.Column('frst_reg_user_id', sa.String(), nullable=True),
    sa.Column('last_reg_user_id', sa.String(), nullable=True),
    sa.Column('last_chg_date', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['scheduler_job_groups.group_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_name', name='workflow_name_table_unique')
    )
    op.create_table('scheduler_job_run_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('celery_task_name', sa.String(), nullable=True),
    sa.Column('log_date', sa.BigInteger(), nullable=True),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('system_name', sa.String(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('job_name', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('batch_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('error_no', sa.Integer(), nullable=True),
    sa.Column('req_start_date', sa.BigInteger(), nullable=True),
    sa.Column('actual_start_date', sa.BigInteger(), nullable=True),
    sa.Column('actual_end_date', sa.BigInteger(), nullable=True),
    sa.Column('run_duration', sa.Interval(), nullable=True),
    sa.Column('additional_info', sa.String(), nullable=True),
    sa.Column('errors', sa.String(), nullable=True),
    sa.Column('output', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['scheduler_job_groups.group_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['scheduler_jobs.job_id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['scheduler_job_servers.system_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('scheduler_job_last_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('job_name', sa.String(), nullable=True),
    sa.Column('actual_start_date', sa.BigInteger(), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('last_state_job', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['scheduler_job_groups.group_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['scheduler_jobs.job_id'], ),
    sa.ForeignKeyConstraint(['log_id'], ['scheduler_job_run_logs.log_id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['scheduler_job_servers.system_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_job_last_log')
    op.drop_table('scheduler_job_run_logs')
    op.drop_table('scheduler_workflow')
    op.drop_table('scheduler_related_group_user')
    op.drop_table('scheduler_jobs')
    op.drop_table('scheduler_job_servers')
    op.drop_table('scheduler_job_groups')
    op.drop_table('scheduler_workflow_priority_group')
    op.drop_table('scheduler_users')
    # ### end Alembic commands ###
