"""empty message

Revision ID: e824feeea8b2
Revises: 1310f247f3b5
Create Date: 2025-08-14 13:04:00.231869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e824feeea8b2'
down_revision = '1310f247f3b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_jobs', sa.Column('state_before_disable', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_jobs', 'state_before_disable')
    # ### end Alembic commands ###
