"""empty message

Revision ID: ee2c9930628c
Revises: ff7561e21cec
Create Date: 2025-08-28 19:04:56.304224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2c9930628c'
down_revision = 'ff7561e21cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_workflow', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_workflow', 'timezone')
    # ### end Alembic commands ###
