"""empty message

Revision ID: ff7561e21cec
Revises: e824feeea8b2
Create Date: 2025-08-25 17:24:33.047225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7561e21cec'
down_revision = 'e824feeea8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_workflow_run',
    sa.Column('workflow_run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('start_date', sa.BigInteger(), nullable=True),
    sa.Column('end_date', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['scheduler_workflow.id'], ),
    sa.PrimaryKeyConstraint('workflow_run_id')
    )
    op.create_index('idx_wf_run_start_date', 'scheduler_workflow_run', ['start_date'], unique=False)
    op.create_index('idx_wf_run_status', 'scheduler_workflow_run', ['status'], unique=False)
    op.add_column('scheduler_job_run_logs', sa.Column('workflow_run_id', sa.Integer(), nullable=True))
    op.add_column('scheduler_job_run_logs', sa.Column('workflow_priority', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scheduler_job_run_logs', 'scheduler_workflow_run', ['workflow_run_id'], ['workflow_run_id'])
    op.add_column('scheduler_jobs', sa.Column('workflow_delay', sa.Integer(), nullable=True))
    op.add_column('scheduler_workflow', sa.Column('start_date', sa.BigInteger(), nullable=True))
    op.add_column('scheduler_workflow', sa.Column('repeat_interval', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_workflow', 'repeat_interval')
    op.drop_column('scheduler_workflow', 'start_date')
    op.drop_column('scheduler_jobs', 'workflow_delay')
    op.drop_constraint(None, 'scheduler_job_run_logs', type_='foreignkey')
    op.drop_column('scheduler_job_run_logs', 'workflow_priority')
    op.drop_column('scheduler_job_run_logs', 'workflow_run_id')
    op.drop_index('idx_wf_run_status', table_name='scheduler_workflow_run')
    op.drop_index('idx_wf_run_start_date', table_name='scheduler_workflow_run')
    op.drop_table('scheduler_workflow_run')
    # ### end Alembic commands ###
